{% block from %}
FROM jolicode/base:latest
{% endblock %}

{% block content %}
{% endblock %}

LABEL com.jolici.image="true"
ENV WORKDIR $HOME/project
ENV TRAVIS_BUILD_DIR $WORKDIR
ADD . $WORKDIR
WORKDIR $HOME/project
RUN sudo chown travis:travis -R $HOME

{% block env %}{% endblock %}

{% block before_install %}{% endblock %}

{% block install %}{% endblock %}

{% block before_script %}{% endblock %}

{% block script %}{% endblock %}
